language: node_js
node_js:
- "lts/*"
install: npm ci
script:
- echo "Running tests against $(node -v) ..."
- npm test
# before_deploy:
# - pip install urllib3[secure]
# - pip install awscli --upgrade --user
# - yarn build
# - chmod +x scripts/*.sh
# deploy:
#   provider: script
#   script: scripts/deploy.sh
#   skip_cleanup: true
#   on:
#     branch: master
#     node: 8
